spring.datasource.url=jdbc:postgresql://localhost:5432/farmer_procurement
spring.datasource.username=postgres
spring.datasource.password=Psn@3176S

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080